//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentlerAdmin.Data.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public Order()
        {
            this.Buildings = new HashSet<Building>();
            this.OrderItems = new HashSet<OrderItem>();
        }
    
        public int OrderId { get; set; }
        public Nullable<long> BuildingId { get; set; }
        public int UserId { get; set; }
        public Nullable<int> UserCreditCardId { get; set; }
        public decimal OrderTotal { get; set; }
        public string PromoCode { get; set; }
        public System.DateTime CreateDate { get; set; }
        public int OrderStatusCode { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual ICollection<Building> Buildings { get; set; }
        public virtual Building Building { get; set; }
        public virtual ICollection<OrderItem> OrderItems { get; set; }
        public virtual UserCreditCard UserCreditCard { get; set; }
        public virtual User User { get; set; }
    }
}
