//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentlerAdmin.Data.Core
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public DbSet<AffiliateUser> AffiliateUsers { get; set; }
        public DbSet<ApiKey> ApiKeys { get; set; }
        public DbSet<BuildingAmenity> BuildingAmenities { get; set; }
        public DbSet<Building> Buildings { get; set; }
        public DbSet<ContactInfo> ContactInfoes { get; set; }
        public DbSet<CustomAmenity> CustomAmenities { get; set; }
        public DbSet<FeaturedListing> FeaturedListings { get; set; }
        public DbSet<OrderItem> OrderItems { get; set; }
        public DbSet<Order> Orders { get; set; }
        public DbSet<Photo> Photos { get; set; }
        public DbSet<SavedBuilding> SavedBuildings { get; set; }
        public DbSet<UserApplication> UserApplications { get; set; }
        public DbSet<UserBank> UserBanks { get; set; }
        public DbSet<UserCreditCard> UserCreditCards { get; set; }
        public DbSet<UserInterest> UserInterests { get; set; }
        public DbSet<User> Users { get; set; }
        public DbSet<ZipInfo> ZipInfoes { get; set; }
    }
}
