//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RentlerAdmin.Data.Core
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInterest
    {
        public int UserInterestId { get; set; }
        public int UserId { get; set; }
        public long BuildingId { get; set; }
        public string Message { get; set; }
        public string ResponseMessage { get; set; }
        public bool ApplicationSubmitted { get; set; }
    
        public virtual Building Building { get; set; }
        public virtual User User { get; set; }
    }
}
